### ISSUE TITLE
Add non active parent shapes to background

### ISSUE THREAD

**Issue by andreash0** [hoga-it/leafdown#1]
Add non active parent shapes to background. As an example:

![image](https://user-images.githubusercontent.com/33908442/83975983-4c607600-a8f7-11ea-9262-baf5af50fe8b.png)

**Comment by petergandenberger** [comment]
We should add some tests for this aswell

**Comment by andreash0** [comment]
Added required tests to `test-drilling.R`. 
Checks if selected and unselected parents are correct so that the background shapes are displayed correctly after drilldown.

**Comment by petergandenberger** [comment]
Looks great. Thank you!
