### ISSUE TITLE
Drilldown with no selection should add error message

### ISSUE THREAD

**Issue by petergandenberger** [hoga-it/leafdown#10]
Drilling down without selection works.
It should show an error message

**Comment by andreash0** [comment]
Cannot reproduce this exact issue with the other map

![image](https://user-images.githubusercontent.com/33908442/90952344-257bff80-e463-11ea-8a6b-901b7ff00a8f.png)

However, if I first select a shape and then unselect it and try to drill down again (so no shape selected) I get this (unintended) error message.

![image](https://user-images.githubusercontent.com/33908442/90952367-5d834280-e463-11ea-8a4e-3e3c4987c99a.png)

**Comment by andreash0** [comment]
@petergandenberger  Could you please try if your issue appears in the german app too?

**Comment by andreash0** [comment]
Is there any possibility to test this in testthat?

**Comment by petergandenberger** [comment]
A simple test would be to check that there are no error-messages....

**Comment by petergandenberger** [comment]
Added a test.
