### ISSUE TITLE
Improve roxygen documentation

### ISSUE THREAD

**Issue by andreash0** [hoga-it/leafdown#20]
- [x] Explain  in `$add_data` method that the data are not allowed to be reshuffled etc.
- [x] Specify `@return` statement in `check_join_map_levels_by` function
- [x] Format bullet points in `$drill_down()` and  `$drill_up()`
- [x] remove "Every element must have a GID_1" from check_helpers "check_spdf_list"

**Comment by petergandenberger** [comment]
Looks good
