### ISSUE TITLE
Code in demo app

### ISSUE THREAD

**Issue by williamlai2** [hoga-it/leafdown#24]
Is the code in the demo app correct? It doesn't seem to run.

https://hoga-it.github.io/leafdown/articles/Showcase_electionapp.html

Possible issues:
*  no `shinyApp(ui, server)` at end
* `output$party` and `output$socio` are outside of `server`.

I have downloaded the state and county files, but even then, it still doesn't seem to run.

**Comment by andreash0** [comment]
You are right - there was an error.

I think I fixed it now. Could you please try it if it also works for you?

**Comment by williamlai2** [comment]
The code in the 'The full code of the election map…' on that page doesn't seem to have changed.

**Comment by andreash0** [comment]
Sorry forget to rebuild the pkgdown site  - now it's updated

**Comment by williamlai2** [comment]
Great. Thanks.
