### ISSUE TITLE
Support for more than 2 map levels?

### ISSUE THREAD

**Issue by dgoldwx2112** [hoga-it/leafdown#27]
When attempting to incorporate a third map level I get the error "Leafdown currently supports only two map levels. The given spdf_list can therefore only contain two elements." Is multi-layer drilldown in the plans by any chance?

**Comment by petergandenberger** [comment]
Hi,
we are happy, that you like the package.
Multi-Layer support is definitely planned.
We will try to tackle this over the Christmas holidays.

**Comment by petergandenberger** [comment]
Steps needed

- [x] change .selected_parentsand .unselected_parents into lists 
- [x] extend .join_map_levels_by list
- [x] extend drill_up
- [x] extend drill_down
- [x] add example
- [x] adapt documentation
- [x] add tests
