### ISSUE TITLE
Sample App with Brazilian Maps

### ISSUE THREAD

**Issue by ragapack** [hoga-it/leafdown#35]
Hi,
To make some test I modyfied you sample App to the Brazilian State and Municipality layers from tha Raster package and saved the layers as a .Rda file.

The app opens fine.
![image](https://user-images.githubusercontent.com/6429531/185785007-ea4c3784-a002-4517-ac65-8b63d1fd0de5.png)

But when I drill down I get this error message:
_Warning: Error in my_leafdown$add_data: You cannot change or reorder the existing meta-data. Only add to it. Use left_joins to avoid reordering. Error: Component “GID_0”: Lengths (241, 22) differ (string compare on first 22)You cannot change or reorder the existing meta-data. Only add to it. Use left_joins to avoid reordering. Error: Component “NAME_0”: Lengths (241, 22) differ (string compare on first 22)You cannot change or reorder the existing meta-data. Only add to it. Use left_joins to avoid reordering. Error: Component “GID_1”: Lengths (241, 22) differ (string compare on first 22)You cannot change or reorder the existing meta-data. Only add to it. Use left_joins to avoid reordering. Error: Component “NAME_1”: Lengths (241, 22) differ (string compare on first 22)You cannot change or reorder the existing meta-data. Only add to it. Use left_joins to avoid reordering. Error: Component “NL_NAME_1”: Lengths (241, 22) differ (string compare on first 22)You cannot change or re [... truncated]

The State file is OK one line for each state

GID_0 NAME_0    GID_1              NAME_1            VARNAME_1 NL_NAME_1           TYPE_1        ENGTYPE_1 CC_1 HASC_1 PIB_per_Capta
1    BRA Brazil  BRA.1_1                Acre                 <NA>      <NA>           Estado            State <NA>  BR.AC         15630
2    BRA Brazil  BRA.2_1             Alagoas                 <NA>      <NA>           Estado            State <NA>  BR.AL         58964
3    BRA Brazil  BRA.3_1               Amapá                 <NA>      <NA>           Estado            State <NA>  BR.AP         17497
4    BRA Brazil  BRA.4_1            Amazonas              Amazone      <NA>           Estado            State <NA>  BR.AM        108181
5    BRA Brazil  BRA.5_1               Bahia                 Ba¡a      <NA>           Estado            State <NA>  BR.BA        293241
6    BRA Brazil  BRA.6_1               Ceará                 <NA>      <NA>           Estado            State <NA>  BR.CE        163575
7    BRA Brazil  BRA.7_1    Distrito Federal                 <NA>      <NA> Distrito Federal Federal District <NA>  BR.DF        273614
8    BRA Brazil  BRA.8_1      Espírito Santo       Espiritu Santo      <NA>           Estado            State <NA>  BR.ES        137346
9    BRA Brazil  BRA.9_1               Goiás          Goiáz|Goyáz      <NA>           Estado            State <NA>  BR.GO        208672
10   BRA Brazil BRA.10_1            Maranhão São Luíz de Maranhão      <NA>           Estado            State <NA>  BR.MA         97340
11   BRA Brazil BRA.12_1         Mato Grosso         Matto Grosso      <NA>           Estado            State <NA>  BR.MT        142122
12   BRA Brazil BRA.11_1  Mato Grosso do Sul                 <NA>      <NA>           Estado            State <NA>  BR.MS        106943
13   BRA Brazil BRA.13_1        Minas Gerais   Minas|Minas Geraes      <NA>           Estado            State <NA>  BR.MG        651873
14   BRA Brazil BRA.14_1                Pará                 <NA>      <NA>           Estado            State <NA>  BR.PA        178377
15   BRA Brazil BRA.15_1             Paraíba             Parahyba      <NA>           Estado            State <NA>  BR.PB         67986
16   BRA Brazil BRA.16_1              Paraná                 <NA>      <NA>           Estado            State <NA>  BR.PR        466377
17   BRA Brazil BRA.17_1          Pernambuco           Pernambouc      <NA>           Estado            State <NA>  BR.PE        197853
18   BRA Brazil BRA.18_1               Piauí               Piauhy      <NA>           Estado            State <NA>  BR.PI         52781
19   BRA Brazil BRA.19_1      Rio de Janeiro                 <NA>      <NA>           Estado            State <NA>  BR.RJ        779928
20   BRA Brazil BRA.20_1 Rio Grande do Norte                 <NA>      <NA>           Estado            State <NA>  BR.RN         71337
21   BRA Brazil BRA.21_1   Rio Grande do Sul                 <NA>      <NA>           Estado            State <NA>  BR.RS        482464
22   BRA Brazil BRA.22_1            Rondônia              Guaporé      <NA>           Estado            State <NA>  BR.RO         47091
23   BRA Brazil BRA.23_1             Roraima           Rio Branco      <NA>           Estado            State <NA>  BR.RR         14292
24   BRA Brazil BRA.24_1      Santa Catarina      Santa Catharina      <NA>           Estado            State <NA>  BR.SC        323264
25   BRA Brazil BRA.25_1           São Paulo                 <NA>      <NA>           Estado            State <NA>  BR.SP       2348338
26   BRA Brazil BRA.26_1             Sergipe                 <NA>      <NA>           Estado            State <NA>  BR.SE         44689
27   BRA Brazil BRA.27_1           Tocantins                 <NA>      <NA>           Estado            State <NA>  BR.TO         39356

But the Municipality file now has more lines for each Municipality.

   GID_0 NAME_0   GID_1 NAME_1 NL_NAME_1     GID_2          NAME_2 VARNAME_2 NL_NAME_2    TYPE_2    ENGTYPE_2 CC_2 HASC_2 PIB_per_Capta 
1    BRA Brazil BRA.1_1   Acre      <NA> BRA.1.1_1      Acrelândia      <NA>      <NA> Município Municipality <NA>   <NA>          9724
2    BRA Brazil BRA.1_1   Acre      <NA> BRA.1.1_1      Acrelândia      <NA>      <NA> Município Municipality <NA>   <NA>         11172
3    BRA Brazil BRA.1_1   Acre      <NA> BRA.1.1_1      Acrelândia      <NA>      <NA> Município Municipality <NA>   <NA>         12466
4    BRA Brazil BRA.1_1   Acre      <NA> BRA.1.1_1      Acrelândia      <NA>      <NA> Município Municipality <NA>   <NA>         16075
5    BRA Brazil BRA.1_1   Acre      <NA> BRA.1.1_1      Acrelândia      <NA>      <NA> Município Municipality <NA>   <NA>         15266
6    BRA Brazil BRA.1_1   Acre      <NA> BRA.1.1_1      Acrelândia      <NA>      <NA> Município Municipality <NA>   <NA>         15355
7    BRA Brazil BRA.1_1   Acre      <NA> BRA.1.1_1      Acrelândia      <NA>      <NA> Município Municipality <NA>   <NA>         16970
8    BRA Brazil BRA.1_1   Acre      <NA> BRA.1.1_1      Acrelândia      <NA>      <NA> Município Municipality <NA>   <NA>         15985
9    BRA Brazil BRA.1_1   Acre      <NA> BRA.1.1_1      Acrelândia      <NA>      <NA> Município Municipality <NA>   <NA>         16853
10   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.1_1      Acrelândia      <NA>      <NA> Município Municipality <NA>   <NA>         16624
11   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.2_1    Assis Brazil      <NA>      <NA> Município Municipality <NA>   <NA>          <NA>
12   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.3_1       Brasiléia      <NA>      <NA> Município Municipality <NA>   <NA>          8895
13   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.3_1       Brasiléia      <NA>      <NA> Município Municipality <NA>   <NA>          9318
14   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.3_1       Brasiléia      <NA>      <NA> Município Municipality <NA>   <NA>         10723
15   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.3_1       Brasiléia      <NA>      <NA> Município Municipality <NA>   <NA>         12877
16   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.3_1       Brasiléia      <NA>      <NA> Município Municipality <NA>   <NA>         14583
17   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.3_1       Brasiléia      <NA>      <NA> Município Municipality <NA>   <NA>         16274
18   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.3_1       Brasiléia      <NA>      <NA> Município Municipality <NA>   <NA>         15981
19   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.3_1       Brasiléia      <NA>      <NA> Município Municipality <NA>   <NA>         15668
20   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.3_1       Brasiléia      <NA>      <NA> Município Municipality <NA>   <NA>         17005
21   BRA Brazil BRA.1_1   Acre      <NA> BRA.1.3_1       Brasiléia      <NA>      <NA> Município Municipality <NA>   <NA>         17307

Here my code,

```
library(leafdown)
library(leaflet)
library(shiny)
library(dplyr)
library(shinyjs)

bra1 <- readRDS("/srv/shiny-server/leafdown/sample/bra1.Rda")
bra2 <- readRDS("/srv/shiny-server/leafdown/sample/bra2.Rda")

bra1_Data <- read.csv(file="PIB dos Estados.csv", header=TRUE, sep=";")
bra2_Data <- read.csv(file="PIB dos Municipios.csv", header=TRUE, sep=";")

spdfs_list <- list(bra1, bra2)

ui <- shiny::fluidPage(
  tags$style(HTML(".leaflet-container {background: #ffffff;}")),
  useShinyjs(),
  actionButton("drill_down", "Drill Down"),
  actionButton("drill_up", "Drill Up"),
  leafletOutput("leafdown", height = 600),
)

#Little helper function for hover labels
create_labels <- function(data, map_level) {
  labels <- sprintf(
    "<strong>%s</strong><br/>%g € per capita</sup>",
    data[, paste0("NAME_", map_level)], data$PIB_per_Capta
  )
  labels %>% lapply(htmltools::HTML)
}

server <- function(input, output) {
  my_leafdown <- Leafdown$new(spdfs_list, "leafdown", input)
  update_leafdown <- reactiveVal(0)
  
  observeEvent(input$drill_down, {
    my_leafdown$drill_down()
    update_leafdown(update_leafdown() + 1)
  })
  
  observeEvent(input$drill_up, {
    my_leafdown$drill_up()
    update_leafdown(update_leafdown() + 1)
  })
  
  output$leafdown <- renderLeaflet({
    update_leafdown()
    meta_data <- my_leafdown$curr_data
    curr_map_level <- my_leafdown$curr_map_level
    
    
    
    
    if (curr_map_level == 1) {
      data <- meta_data %>% dplyr::left_join(bra1_Data, by = c("NAME_1" = "Estado"))
    } else {
      data <- meta_data %>% dplyr::left_join(bra2_Data, by = c("NAME_2" = "Municipio"))
    }
    print(data)
    my_leafdown$add_data(data)
    labels <- create_labels(data, curr_map_level)
    my_leafdown$draw_leafdown(
      fillColor = ~ colorNumeric("Greens", PIB_per_Capta)(PIB_per_Capta),
      weight = 2, fillOpacity = 0.8, color = "grey", label = labels,
      highlight = highlightOptions(weight = 5, color = "#666", fillOpacity = 0.7)
    ) %>% 
      my_leafdown$keep_zoom(input) %>% 
      addLegend("topright",
                pal = colorNumeric("Greens", data$PIB_per_Capta),
                values = data$PIB_per_Capta,
                title = "PIB_per_Capta (2019)",
                labFormat = labelFormat(suffix = "R$"),
                opacity = 1
      )
  })
}


shinyApp(ui, server)
```

**Comment by petergandenberger** [comment]
Hi,

I think the problem is in line 57 
`data <- meta_data %>% dplyr::left_join(bra2_Data, by = c("NAME_2" = "Municipio"))`
You match by "NAME_2" but it seems like that column is not unique for each row, hence you will get more rows after the join.

Try to use more than one column for the join to make each row unique.

You can quickly check if that is the problem by comparing `nrow(data)` and `nrow(meta_data)` after the joins. They should always be the same

If that does not fix your problem please also provide us with your "PIB dos Estados.csv" and "PIB dos Municipios.csv" files (you can change any sensitive data to random values)

Best
Peter

**Comment by ragapack** [comment]
Hi Peter,
Thank you for your answer, I tried this but get the same result 10x for each Municipality
There are the same name of a Municipality in different states but never the same name in the same state.
`data <- meta_data %>% dplyr::left_join(bra2_Data, by = c("NAME_2" = "Municipio", "NAME_1" = "Estado"))`
Here the 2 files of the data for the PIB
[Brasil.zip](https://github.com/hoga-it/leafdown/files/9392269/Brasil.zip)

Thank you a lot
Thomas

**Comment by andreash0** [comment]
HI Thomas,

I just had a look at your data sets.

For some combinations of Municipio and Estado there are several records, e.g.,

```r
bra2_Data %>% dplyr::filter(Estado == "Bahia", Municipio == "Acajutiba")

   Estado Municipio PIB_per_Capta
1   Bahia Acajutiba         84408
2   Bahia Acajutiba         89131
3   Bahia Acajutiba         97105
4   Bahia Acajutiba        109425
5   Bahia Acajutiba        114174
6   Bahia Acajutiba        116674
7   Bahia Acajutiba        119173
8   Bahia Acajutiba        120754
9   Bahia Acajutiba        133741
10  Bahia Acajutiba        127040
```

In this case leafdown does not know which value to use and thus throws this error.
There needs to be one value per combination of Estado and Municipio.

Best
Andreas

**Comment by ragapack** [comment]
Hi Peter, Hi Andreas,
Now it works fine, the problem was more then 1 value for each Municipio. I downloaded an other table of data and this give me 1 line for each Municipio.
Other problem was in the maps from the raster package, the names of the Municipios differ from the official spelling.
So I use now a brazilian package.
https://github.com/ipeaGIT/geobr
Here my code changes:

```
...
library(geobr)
library(sf)

bra1 <- read_state()
bra2 <- read_municipality(year=2018) 

colnames(bra1)[which(names(bra1) == "name_state")] <- "NAME_1"
colnames(bra2)[which(names(bra2) == "name_muni")] <- "NAME_2"

bra1 <- as_Spatial(bra1)
bra2 <- as_Spatial(bra2)
...
```
![image](https://user-images.githubusercontent.com/6429531/187027563-b917b5f6-2489-493e-b4a3-37ff64424015.png)
