### ISSUE TITLE
Ignore 'bringToFront' = TRUE in highlightOptions

### ISSUE THREAD

**Issue by andreash0** [hoga-it/leafdown#5]
If the `bringToFront` argument in the `highlightOptions` is set to `TRUE` it collides with our internal highlighting of selected shapes. I think for the beginning we should always set this to `FALSE` and give a warning/message that we set it to `FALSE` if the user sets it to `TRUE`
 
```r
map <- my_leafdown$draw_leafdown(
      fillColor = ~ colorNumeric("Blues", GDP_2014)(GDP_2014),
      highlight = highlightOptions(
        weight = 5,
        color = "#666",
        fillOpacity = 0.7,
        bringToFront = TRUE)
  )
```

**Comment by andreasho95** [comment]
On hold until https://github.com/rstudio/shinytest/pull/344 is fixed.
This makes testing the issue much easier and avoids creating a large number of test apps.

**Comment by andreash0** [comment]
`$draw_leafdown` now returns a warning message "The argument 'bringToFront' in 'highlightOptions' is used internally by leafdown and is therefore ignored." when 'bringToFront' is set in highlightOptions (regardsless of whether set to `TRUE` or `FALSE`) and ignores the argument.

**Comment by petergandenberger** [comment]
Looks good. Thank you :)
