### ISSUE TITLE
$draw_leafdown method returns unexpected map when argument 'dashArray' in 'highlightOptions' is set

### ISSUE THREAD

**Issue by andreash0** [hoga-it/leafdown#6]
In case we specify the argument 'dashArray' in 'highlightOptions' only one shape is drawn.
```r
map <- my_leafdown$draw_leafdown(
      fillColor = ~ colorNumeric("Blues", GDP_2014)(GDP_2014),
      weight = 2, fillOpacity = 0.8, color = "grey", label = labels,
      highlight = highlightOptions(
        weight = 5,
        color = "#666",
        dashArray = "",
        fillOpacity = 0.7,
        bringToFront = FALSE)
    )
```
![image](https://user-images.githubusercontent.com/33908442/84590520-ac937280-ae37-11ea-9641-5619ecfd5678.png)

**Comment by andreasho95** [comment]
On hold until https://github.com/rstudio/shinytest/pull/344 is fixed.
This makes testing the issue much easier and avoids creating a large number of test apps.

**Comment by petergandenberger** [comment]
Looks good, thank you.
