### ISSUE TITLE
Don't accept "layerId" as argument in "$draw_leafdown" method

### ISSUE THREAD

**Issue by andreash0** [hoga-it/leafdown#7]
We mustn't accept "layerId" as argument in "$draw_leafdown" method as we use it internally. 
Otherwise we would specify the argument multiple times and generate an error.
```r
draw_leafdown = function(...) {
   ...
   map <- leaflet::leaflet(curr_spdf) %>%
        leaflet::addPolygons(layerId = ~all_poly_ids, ...) %>%
        addPolylines(
          group = all_poly_ids, stroke = TRUE, weight = 4, color = "#FFCC00",
          highlight = highlightOptions(bringToFront = T, weight = 4)
        )
   ...
}
```
```r
my_leafdown$draw_leafdown(layerId = some_layer_ids)
```
An approach might be to return a warning message like ' "layerId" cannot be set from outside and is therefore ignored' and ignore the argument in case "layerId" is among the arguments

**Comment by andreash0** [comment]
On hold until https://github.com/rstudio/shinytest/pull/344 is fixed.
This makes testing the issue much easier and avoids creating a large number of test apps.

**Comment by andreash0** [comment]
Returns now warning message "The argument 'layerId' is used internally by leafdown and is therefore ignored" if argument is set and ignores it in $draw_leafdown

**Comment by petergandenberger** [comment]
Looks good. Thank you :)
