### ISSUE TITLE
Reordering the data throws error.

### ISSUE THREAD

**Issue by petergandenberger** [hoga-it/leafdown#9]
Adding data to the map with reordered metadata throws an error. 
This is ok. But I think we should make the error message a bit better or try to reorder back ourself.

**Comment by andreash0** [comment]
@petergandenberger Could you add a reprex of it pls? Would make testing easier after fixing.

**Comment by petergandenberger** [comment]
Simply adding `data <- data[order(data$y), ]` before `my_leafdown$add_data(data)` should show the error.

**Comment by petergandenberger** [comment]
If we reorder the data in the add_data method there might be inconsistencies.
The data the user uses to color the map will be ordered differently to the internal ordering.

Therefore I added a better error message.
